"""Dependency-free shared kernel."""

from __future__ import annotations

from .card_scripts import CardScripts
from .decisions import (
    DECISION_COLUMNS,
    DECISION_FIELD_TYPE,
    DECISION_RESOLUTIONS_BY_TYPE,
    DECISION_TYPES,
    DEFAULT_STATE_TEMPLATE,
    MAX_CHOICE_OPTIONS,
    MAX_SCORE_LEVELS,
    MIN_SCORE_LEVELS,
    OUTCOME_KEYS,
    DecisionDefinition,
    decision_definition_errors,
    is_decision_row,
    parse_decision_definition,
)
from .domain_types import CastMember, GroupContextMode, TurnCast
from .fragment_state import (
    DEFAULT_STATE_INJECT,
    DEFAULT_STATE_MODE,
    DEFAULT_STATE_UPDATE,
    MAX_ACTIVE_ENTRIES,
    MAX_STATE_TEXT_CHARS,
    STATE_COLUMNS,
    STATE_FIELD_TYPE,
    STATE_INJECTS,
    STATE_MODES,
    STATE_UPDATES,
    StateEntry,
    StateFragment,
    StateOp,
    StateRejection,
    StateView,
    carry_events,
    fold_events,
    full_fragments,
    is_state_row,
    legacy_state_settings,
    plan_state_ops,
    state_fragment_of,
    state_fragments_of,
    upgrade_legacy_fragment,
    value_text,
)
from .llm_types import (
    AssistantToolMessage,
    ChatMessage,
    ContentPart,
    WireMessage,
)
from .locks import (
    maintenance_lock,
    wal_anchor_lock,
    workflow_character_state_lock,
    workflow_config_lock,
    workflow_state_lock,
    world_apply_lock,
)
from .macros import (
    Macros,
    card_description,
    has_inline_macros,
    outside_literals,
    resolve_inline,
    resolve_stored_random,
)
from .reasoning import (
    CALL_BREAK,
    ReasoningChannel,
    joined_delta,
    mark_call_start,
    reasoning_delta_event,
)
from .text_segmentation import (
    ends_with_sentence_terminator,
    find_quote_spans,
    remove_quoted_spans,
    split_sentences,
)
from .utils import (
    agent_lane_cut_off,
    agent_lane_max_tokens,
    build_multimodal_content,
    estimate_tokens,
    extract_hyperparams,
    scrub_log,
)

__all__ = [
    # llm_types — wire contracts
    "AssistantToolMessage",
    "ChatMessage",
    "ContentPart",
    "WireMessage",
    "CastMember",
    "GroupContextMode",
    "TurnCast",
    # decisions — the decision-fragment authoring contract
    "DECISION_COLUMNS",
    "DECISION_FIELD_TYPE",
    "DECISION_RESOLUTIONS_BY_TYPE",
    "DECISION_TYPES",
    "DEFAULT_STATE_TEMPLATE",
    "MAX_CHOICE_OPTIONS",
    "MAX_SCORE_LEVELS",
    "MIN_SCORE_LEVELS",
    "OUTCOME_KEYS",
    "DecisionDefinition",
    "decision_definition_errors",
    "is_decision_row",
    "parse_decision_definition",
    # fragment_state — state-fragment configuration, fold, and operation contract
    "DEFAULT_STATE_INJECT",
    "DEFAULT_STATE_MODE",
    "DEFAULT_STATE_UPDATE",
    "MAX_ACTIVE_ENTRIES",
    "MAX_STATE_TEXT_CHARS",
    "STATE_COLUMNS",
    "STATE_FIELD_TYPE",
    "STATE_INJECTS",
    "STATE_MODES",
    "STATE_UPDATES",
    "StateEntry",
    "StateFragment",
    "StateOp",
    "StateRejection",
    "StateView",
    "carry_events",
    "fold_events",
    "full_fragments",
    "is_state_row",
    "legacy_state_settings",
    "plan_state_ops",
    "state_fragment_of",
    "state_fragments_of",
    "upgrade_legacy_fragment",
    "value_text",
    # locks — process-level asyncio locks
    "maintenance_lock",
    "wal_anchor_lock",
    "workflow_character_state_lock",
    "workflow_config_lock",
    "workflow_state_lock",
    "world_apply_lock",
    # macros — string/message transforms
    "Macros",
    "CardScripts",
    "card_description",
    "has_inline_macros",
    "outside_literals",
    "resolve_inline",
    "resolve_stored_random",
    # reasoning — per-pass thinking buffers (one blank line between calls)
    "CALL_BREAK",
    "ReasoningChannel",
    "joined_delta",
    "mark_call_start",
    "reasoning_delta_event",
    # text_segmentation — canonical non-workflow prose policy
    "ends_with_sentence_terminator",
    "find_quote_spans",
    "remove_quoted_spans",
    "split_sentences",
    # utils — token/log/multimodal helpers
    "agent_lane_cut_off",
    "agent_lane_max_tokens",
    "build_multimodal_content",
    "estimate_tokens",
    "extract_hyperparams",
    "scrub_log",
]
