from __future__ import annotations

import random
from datetime import UTC, datetime, timedelta

from ..connection import get_db

# Seeds settings.generated_chars from the rows that already exist the first
# time the counter is touched (NULL = never seeded). Assistant rows across ALL
# branches (swipes/regens are sibling rows) approximate what the LLM has
# generated historically; after this one-time backfill the counter only moves
# via add_generated_chars, so deleting conversations no longer shrinks it.
_SEED_GENERATED_CHARS_SQL = """
    UPDATE settings
    SET generated_chars = (
        SELECT COALESCE(SUM(LENGTH(content)), 0) FROM messages WHERE role = 'assistant'
    )
    WHERE id = 1 AND generated_chars IS NULL
"""


async def get_generated_chars() -> int:
    """Lifetime characters generated by the LLM (callers derive tokens).

    Seeds the counter from existing assistant messages on first use.
    """
    async with get_db() as db:
        rows = list(await db.execute_fetchall("SELECT generated_chars FROM settings WHERE id = 1"))
        if rows and rows[0][0] is not None:
            return int(rows[0][0])
        # Only the unseeded read writes; every later homepage load is a plain
        # read rather than a write transaction. The seed's own IS NULL guard
        # keeps a racing add_generated_chars from being seeded twice.
        await db.execute(_SEED_GENERATED_CHARS_SQL)
        await db.commit()
        rows = list(await db.execute_fetchall("SELECT generated_chars FROM settings WHERE id = 1"))
        return int(rows[0][0]) if rows and rows[0][0] is not None else 0


async def add_generated_chars(chars: int) -> None:
    """Credit *chars* of freshly generated text to the lifetime counter.

    Call AFTER the assistant message is persisted: if the counter was never
    seeded, the seed scan already counts that new row, so the increment is
    skipped for exactly that case (cur.rowcount == 1) to avoid double counting.
    """
    if chars <= 0:
        return
    async with get_db() as db:
        cur = await db.execute(_SEED_GENERATED_CHARS_SQL)
        if cur.rowcount == 0:
            await db.execute(
                "UPDATE settings SET generated_chars = generated_chars + ? WHERE id = 1",
                (chars,),
            )
        await db.commit()


# Recursive CTE yielding one row per message on a conversation's *active* branch
# (root→active_leaf). Swiped/regenerated siblings are alternate branches the user
# isn't currently viewing, so they're excluded everywhere a message COUNT is shown
# -- they're drafts/trash, not part of the visible story. Exposes conv_id, id and
# created_at so callers can group by conversation and apply recency filters.
_ACTIVE_PATH_CTE = """
    WITH RECURSIVE active_path(conv_id, id, parent_id, created_at, role, speaker_member_id) AS (
        SELECT c.id, m.id, m.parent_id, m.created_at, m.role, m.speaker_member_id
        FROM conversations c
        JOIN messages m ON m.id = c.active_leaf_id
        UNION ALL
        SELECT ap.conv_id, m.id, m.parent_id, m.created_at, m.role, m.speaker_member_id
        FROM active_path ap
        JOIN messages m ON m.id = ap.parent_id
    )
"""

# One row per message a character *wrote*, keyed by the name it wrote under:
# the conversation's for a solo chat, the speaking member's for a group. Both
# arms count assistant rows only. A group's user messages carry no
# ``speaker_member_id`` and so cannot be attributed to a member at all, and
# counting solo user rows against the character would leave a cast member at
# half a solo character's total for the same output -- never the favourite, and
# reaching the "missed you" threshold at twice the play.
_CHARACTER_USAGE_CTE = """
    , character_usage AS (
        SELECT c.character_name AS character_name, c.character_card_id AS card_id,
               c.id AS conv_id, ap.created_at AS created_at
        FROM active_path ap
        JOIN conversations c ON c.id = ap.conv_id
        WHERE c.kind = 'solo' AND ap.role = 'assistant' AND c.character_name != ''
        UNION ALL
        SELECT gm.display_name, gm.character_card_id, c.id, ap.created_at
        FROM active_path ap
        JOIN conversations c ON c.id = ap.conv_id
        JOIN group_members gm ON gm.id = ap.speaker_member_id
        WHERE c.kind = 'group' AND ap.role = 'assistant' AND gm.display_name != ''
    )
"""


async def get_global_stats() -> dict:
    """Aggregate usage stats across the whole database.

    Token totals are NOT derived here -- they come from the persistent
    ``generated_chars`` counter via :func:`get_generated_chars`.
    """
    async with get_db() as db:
        conv_row = list(await db.execute_fetchall("SELECT COUNT(*) FROM conversations"))
        total_conversations = conv_row[0][0] if conv_row else 0

        # "words written" sums role='user' content across ALL branches: every user
        # message was genuinely typed, even on swiped-away forks, so it reflects
        # total effort rather than what's currently visible.
        chars_row = list(
            await db.execute_fetchall("SELECT COALESCE(SUM(LENGTH(content)), 0) FROM messages WHERE role = 'user'")
        )
        user_chars = chars_row[0][0] if chars_row else 0

        # One walk of every conversation's active branch answers both the message
        # count and the per-character tallies the spotlight chooses from: the
        # nameless row carries the count (character_usage never yields a NULL
        # name), the rest one character each. Swiped or regenerated siblings are
        # trash and are not on the branch. A walk per question cost three.
        usage_rows = list(
            await db.execute_fetchall(
                f"""{_ACTIVE_PATH_CTE}{_CHARACTER_USAGE_CTE}
                   SELECT NULL, (SELECT COUNT(*) FROM active_path), NULL, NULL, NULL
                   UNION ALL
                   SELECT character_name,
                          COUNT(*),
                          COUNT(DISTINCT conv_id),
                          MAX(card_id),
                          MAX(created_at)
                   FROM character_usage
                   GROUP BY character_name"""
            )
        )
        total_messages = next((row[1] for row in usage_rows if row[0] is None), 0)
        characters = [row for row in usage_rows if row[0] is not None]

        def _spotlight(row) -> dict:
            return {"name": row[0], "messages": row[1], "conversations": row[2], "card_id": row[3]}

        # Favorite character = the one who wrote the most messages. Grouped on
        # character_name (not card id) so renamed/deleted cards still tally.
        favorite = max(characters, key=lambda row: row[1], default=None)
        favorite_character = _spotlight(favorite) if favorite else None

        # A random well-worn character (>100 messages) for the "misses you"
        # spotlight theme. Excludes the favorite itself so the two themes stay
        # distinct, and anyone talked to in the last 24h — they can't "miss you"
        # if you just spoke. created_at is an ISO-8601 UTC string, so a string
        # compare against the cutoff sorts correctly. The endpoint flips the coin
        # on which theme actually shows.
        recent_cutoff = (datetime.now(UTC) - timedelta(hours=24)).isoformat()
        missed = [
            row for row in characters if row is not favorite and row[1] > 100 and row[4] is not None and row[4] < recent_cutoff
        ]
        missed_character = _spotlight(random.choice(missed)) if missed else None

        # > 0 (not just IS NOT NULL): turns with no LLM passes log 0, and
        # averaging those in would understate true response time.
        lat_row = list(
            await db.execute_fetchall("SELECT AVG(agent_latency_ms) FROM conversation_logs WHERE agent_latency_ms > 0")
        )
        avg_latency = lat_row[0][0] if lat_row else None

        return {
            "total_conversations": total_conversations,
            "total_messages": total_messages,
            "user_chars": user_chars,
            "favorite_character": favorite_character,
            "missed_character": missed_character,
            "avg_latency_ms": avg_latency,
        }
