"""Enrollment against the real speaker encoder, when it is on disk.

Skipped without ``onnxruntime`` or the artifact, so this is a check that runs on
a machine set up for the feature rather than one that blocks every other suite.

A NOTE ON THE FIXTURE BELOW. An early version of the plan's fidelity probe
hard-coded these 32 integers transcribed from a truncated ``[3363, 2367, ...]``
print, inventing the last twenty. It reported 0% agreement for the clone AND the
control — indistinguishable, because neither matched a speaker that existed —
and the bug was caught only because the script also asserted that re-enrolling
the reference reproduced them. So: this fixture was generated by torch, never
typed, and ``test_reproduces_the_torch_reference`` is what keeps it honest. Any
future fixture holding speaker tokens must be checked against a fresh
enrollment the same way.
"""

from __future__ import annotations

import os

import pytest

np = pytest.importorskip("numpy")
pytest.importorskip("onnxruntime")

from backend.inference.local_models.spark_tts import (  # noqa: E402
    catalog,
    enroll,
    tokens,
)

# `real_model_dir` because this suite is about a real model's real output, which
# is the one thing conftest's empty-model-dir fixture exists to prevent tests
# from depending on. The exemption is narrow and safe: every test here skips
# when the artifact is absent, so a machine without it — CI included — runs
# nothing rather than something different.
pytestmark = [
    pytest.mark.real_model_dir,
    pytest.mark.skipif(
        not os.path.exists(catalog.speaker_encoder_path()),
        reason="speaker encoder not downloaded (scripts/export_spark_speaker_encoder.py)",
    ),
]

#: What torch's ``BiCodec.speaker_encoder.tokenize`` produces for upstream's
#: ``example/prompt_audio.wav``, via the full wav2vec2 pipeline AND via the
#: mel-only path, which were verified bit-identical.
_PROMPT_AUDIO_TOKENS = [
    3363, 2367, 1591, 3625, 294, 3556, 1198, 2646,
    3397, 3778, 2459, 3109, 1017, 3860, 3178, 3414,
    1727, 561, 1096, 3133, 3647, 3178, 2767, 73,
    2418, 1838, 3645, 2338, 3451, 2144, 306, 2799,
]  # fmt: skip

_REFERENCE_WAV = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))),
    "..",
    "OrbTTS",
    "vendor",
    "Spark-TTS",
    "example",
    "prompt_audio.wav",
)


def test_enrollment_shape_and_range():
    """Any signal enrolls to 32 in-range codes — including degenerate ones,
    which is what an empty or silent upload reaches this code as."""
    for signal in (
        np.zeros(96000, dtype=np.float32),
        (np.random.default_rng(0).standard_normal(96000) * 0.1).astype(np.float32),
        np.ones(1000, dtype=np.float32) * 0.2,  # shorter than the window; tiled
    ):
        got = enroll.enroll_signal(signal)
        assert tokens.validate_speaker_tokens(got) == got


def test_enrollment_is_deterministic():
    """The stored 32 ints are a reproduction record, not a snapshot of one run:
    a model bump must be able to re-enroll the retained clip and get the voice
    the character already had."""
    signal = (np.random.default_rng(3).standard_normal(96000) * 0.1).astype(np.float32)
    assert enroll.enroll_signal(signal) == enroll.enroll_signal(signal)


def test_different_signals_enroll_differently():
    """Guards the failure the plan's probe hit: a path that returns the same
    tokens regardless of input makes every voice look equally cloned."""
    rng = np.random.default_rng(11)
    a = enroll.enroll_signal(rng.standard_normal(96000).astype(np.float32) * 0.1)
    b = enroll.enroll_signal(np.zeros(96000, dtype=np.float32))
    assert a != b


@pytest.mark.skipif(not os.path.exists(_REFERENCE_WAV), reason="upstream reference clip not checked out")
def test_reproduces_the_torch_reference():
    """The torch-free path, against what torch says, on real speech.

    This is the assertion the whole enrollment design rests on: mel + 24 MB of
    ONNX, with no wav2vec2 and no BiCodec encoder, is the SAME answer.
    """
    with open(_REFERENCE_WAV, "rb") as handle:
        got, window = enroll.enroll(handle.read(), filename="prompt_audio.wav")
    assert window.shape == (96000,)
    assert got == _PROMPT_AUDIO_TOKENS
